# Generated by Django 4.2.5 on 2023-11-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('compressed_file', models.FileField(upload_to='compressed/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
