# Generated by Django 4.2.5 on 2023-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedfile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
