# Generated by Django 4.2.5 on 2023-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compressedfile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_folder', models.FileField(upload_to='uploads/')),
                ('compressed_folder', models.FileField(upload_to='compressed/')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
