# Generated by Django 4.2.5 on 2023-11-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_compressedfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compressedfile',
            name='uploaded_file',
        ),
    ]
