# Generated by Django 4.2.5 on 2023-11-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_compressedfile_uploaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompressedFolder',
        ),
    ]
