# Generated by Django 4.2.5 on 2023-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_compressedfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_folder', models.FileField(upload_to='compressed_folders/')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='compressedfile',
            name='compressed_file',
            field=models.FileField(upload_to='compressed_files/'),
        ),
    ]
